<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Student [
    <!ELEMENT Student (name, age, address, marks, fess, (class|standard))>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
    <!ELEMENT marks (#PCDATA)>
    <!ELEMENT fess (#PCDATA)>
    <!ELEMENT class (#PCDATA)>
    <!ELEMENT standard (#PCDATA)>
    <!ATTLIST name id CDATA "name">
    <!ATTLIST age class CDATA "standard">
    
]>
<Student>
    <name id="name">Ahmed</name>
    <age class="standard">25</age>
    <address>North Karachi</address>
    <marks>85</marks>
    <fess>10,000</fess>
    <class>10</class>
</Student>